version: '2'

services:
  app:
    image: nobiinuand/radvent
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production
      RAILS_SECRET_KEY_BASE: $RAILS_SECRET_KEY_BASE
      RAILS_DATABASE_HOST: radvent_db
      RAILS_DATABASE_INSTANCE: $RADVENT_DB
      RAILS_DATABASE_USERNAME: $RADVENT_DB_USER
      RAILS_DATABASE_PASSWORD: $RADVENT_DB_PASSWORD
    links:
      - db:radvent_db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: $RADVENT_DB_USER
      POSTGRES_PASSWORD: $RADVENT_DB_PASSWORD
      POSTGRES_DB: $RADVENT_DB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: