version: '2'

services:
  app:
    image: nobiinuand/radvent
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production
      RAILS_SECRET_KEY_BASE: $RAILS_SECRET_KEY_BASE
      DATABASE_URL: $DATABASE_URL
    links:
      - db:radventdb
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: $RADVENT_DB_USER
      POSTGRES_PASSWORD: $RADVENT_DB_PASSWORD
      POSTGRES_DB: $RADVENT_DB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: